# Generated by Django 6.0.6 on 2026-06-16 17:21

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forge_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(
                default=pyotp.random_base32,
                editable=False,
                help_text="Clé secrète TOTP de l'utilisateur (générée automatiquement).",
                max_length=32,
                verbose_name="Secret OTP",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("unverified", "Non vérifié"),
                    ("verified", "Vérifié"),
                    ("blocked", "Bloqué"),
                    ("suspended", "Suspendu"),
                    ("deleted", "Supprimé"),
                    ("deactivated", "Désactivé"),
                ],
                default="unverified",
                max_length=20,
                verbose_name="Statut de vérification",
            ),
        ),
    ]
